Azure can return nil instead of empty list here
This was reported by a customer. While I can't reproduce this locally,
I assume that list_all returns nil instead of empty-array:

    Error: Failed to apply catalog: Puppet detected a problem with the information returned from Azure when accessing azure_vm. The specific error was:
    no implicit conversion of nil into Array

    /opt/puppetlabs/puppet/cache/lib/puppet_x/puppetlabs/azure/provider_arm.rb:148:in `+'
    /opt/puppetlabs/puppet/cache/lib/puppet_x/puppetlabs/azure/provider_arm.rb:148:in `get_all_vms'
    /opt/puppetlabs/puppet/cache/lib/puppet/provider/azure_vm/azure_arm.rb:17:in `instances'